[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.semantic_release] 
version_variable = [
    'teex/__version__.py:__version__',
    'docs/conf.py:release'
]
version_source = 'tag'